version: '3.7'
services:
    backend-producao:
      container_name: back-end-producao
      build:
        context: .
        dockerfile: Dockerfile-prod
      ports:
        - '8081:8081'
      volumes:
        - /Orion/Logs:/app/logs