FROM maven:3.8.5-eclipse-temurin-11-focal
WORKDIR /build
COPY . /build
COPY /target/orionBackendJar.jar /app/orionBackendJar.jar
COPY /src/main/java/br/com/live/reports /app/
RUN apt-get update && \ apt-get -y install sudo
RUN useradd -m docker && echo "docker:docker" | chpasswd && adduser docker sudo
USER docker
RUN sudo apt install ttf-mscorefonts-installer
WORKDIR /app
ENTRYPOINT ["java", "-jar", "-Dspring.profiles.active=prod", "orionBackendJar.jar"]
EXPOSE 8081