insert into orion_parametros (id, valor_str) values ('OBRF_701-REG', 'C188');
insert into orion_parametros (id, valor_str) values ('OBRF_701-NUM_PROC', '50029212720174047201');
insert into orion_parametros (id, valor_int) values ('OBRF_701-IND_PROC', 1);
insert into orion_parametros (id, valor_str) values ('OBRF_701-REG_PAI', 'C180');
insert into orion_parametros (id, valor_int) values ('OBRF_701-COD_CRED', 0);
insert into orion_parametros (id, valor_str) values ('OBRF_702-REG', '1020');
insert into orion_parametros (id, valor_str) values ('OBRF_702-REG_PAI_1', 'C188');
insert into orion_parametros (id, valor_str) values ('OBRF_702-ID_SEC_JUD', 'JOINVILLE SC');
insert into orion_parametros (id, valor_str) values ('OBRF_702-ID_VARA', '2');
insert into orion_parametros (id, valor_int) values ('OBRF_702-IND_NAT_10_ACAO', 1);
insert into orion_parametros (id, valor_int) values ('OBRF_702-IND_NAT_20_ACAO', 2);
insert into orion_parametros (id, valor_str) values ('OBRF_702-DESC_DEC_JUD', 'VLR. EXCLUSÃO DO ICMS DA BASE DE CALCULO DO PIS E CONFINS');
insert into orion_parametros (id, valor_date) values ('OBRF_702-DT_SENT_JUD', '16-jun-2020');
insert into orion_parametros (id, valor_date) values ('OBRF_702-DT_DEC_ADM', '16-jun-2020');
insert into orion_parametros (id, valor_int) values ('OBRF_702-NAT_BC_CRED', 0);
insert into orion_parametros (id, valor_int) values ('OBRF_702-IND_ORIG_CRED', 0);
insert into orion_parametros (id, valor_str) values ('PROC_REFERENCIADO-SERIES', '2');
insert into orion_parametros (id, valor_str) values ('PROC_REFERENCIADO-EMPRESAS', '1');
insert into orion_parametros (id, valor_str) values ('PROC_REFERENCIADO-NATUREZAS', '104,803,883,627,930,264,657,0,660,225,465,325,25,701,823,801,180,421,868,810,422,867,304,360,893');
insert into orion_parametros (id, valor_date) values ('PROC_REFERENCIADO-DATA-INICIAL', '10-NOV-2022');
insert into orion_parametros (id, valor_int) values ('INTEGRACAO_FLUXOGAMA_ATIVO', 1);
insert into orion_parametros (id, valor_int) values ('INTEGRACAO_MOVIMENTOS_PAGSEGURO_ATIVO', 1);
insert into orion_parametros (id, valor_str) values ('INTEGRACAO_MOVIMENTOS_PAGSEGURO_USER', '73303871');
insert into orion_parametros (id, valor_str) values ('INTEGRACAO_MOVIMENTOS_PAGSEGURO_PASSWORD', 'fe4f5db3111c44b6b806d6fd789bed5e');
insert into orion_parametros (id, valor_int) values ('INTEGRACAO_TITULO_PAGAMENTO_ATIVO', 1);
insert into orion_parametros (id, valor_int) values ('INTEGRACAO_SELECAO_PAGAMENTO_ATIVO', 1);