CREATE TABLE ORION_CFC_310 (
        ID VARCHAR2(20) PRIMARY KEY,
        STATUS NUMBER(1),
        COD_ROLO NUMBER(9),
        COD_MOTIVO NUMBER(4),
        COD_ANALISTA NUMBER(5),
        QUANTIDADE NUMBER(12,3),
        PERDA_METROS NUMBER(12,3),
        SIT_SINCRONIZACAO NUMBER(1),
        DATA_SINCRONIZACAO DATE,
        DATA_HORA_BIPAGEM DATE
    );