-- Tabelas DRE

-- RELACIONAMENTO LOJAS X CENTRO DE CUSTO X SUPERVISOR - CONSIDERA DRE

    -- SUPERVISOR DA LOJA
    CREATE TABLE ORION_FIN_001 (
          CNPJ_LOJA VARCHAR2(18) PRIMARY KEY,
          CNPJ_SUPERVISOR VARCHAR2(18) NOT NULL
    );

    -- CONTA CONTÁBIL DA LOJA
    CREATE TABLE ORION_FIN_005 (
      ID NUMBER(9) PRIMARY KEY,
      CNPJ_LOJA VARCHAR2(18) NOT NULL,
      CENTRO_CUSTO NUMBER(6) NOT NULL );

-- CONTA CONTÁBIL – CONSIDERA DRE

    -- CONTA CONTÁBIL CONSIDERA DRE
    CREATE TABLE ORION_FIN_010 (
        CONTA_CONTABIL NUMBER(5) PRIMARY KEY,
        GASTO_VARIAVEL NUMBER(1),
        CUSTO_OCUPACAO NUMBER(1),
        DESPESA_FOLHA NUMBER(1),
        DESPESA_GERAL NUMBER(1),
        DEPRECIACAO NUMBER(1));

-- ORÇAMENTO LOJAS – DRE

    -- ORÇAMENTOS PARA GERAÇÃO DA DRE
        CREATE TABLE ORION_FIN_015 (
            ID NUMBER(9) PRIMARY KEY,
            SEQ_CONSULTA VARCHAR2(50),
            CNPJ_LOJA VARCHAR2(18),
            ANO_ORCAMENTO NUMBER(4),
            MES_ORCAMENTO NUMBER(2),
            TIPO_ORCAMENTO NUMBER(1),
            PROPRIEDADE VARCHAR2(150),
            VAL_PROPRIEDADE NUMBER(12,3))

-- GERAR DRE DAS LOJAS

    -- PARÂMETROS GERAIS
    CREATE TABLE ORION_FIN_020 (
        ANO_DRE NUMBER(4),
        MES_DRE NUMBER(2),
        PERC_ENCARGOS NUMBER(6,2),
        VAL_IMPOSTO_PLANEJAMENTO NUMBER(12,3),
        VAL_CUSTO_VENDA_PRODUTO NUMBER(12,3),
        CONSTRAINT PK_ORION_FIN_020 PRIMARY KEY (ANO_DRE, MES_DRE)
    );

    -- CONCILIAÇÃO LOJAS
    CREATE TABLE ORION_FIN_025 (
        CNPJ_LOJA VARCHAR2(18) PRIMARY KEY,
        VAL_TAXA_CAPTURA NUMBER(12,3),
        VAL_CUSTO_ANTECIPACAO NUMBER(12,3)
    );

    -- DRE GERADA
    CREATE TABLE ORION_FIN_030 (
      ID NUMBER(9) PRIMARY KEY,
      CNPJ_LOJA VARCHAR2(18),
      ANO_DRE NUMBER(4),
      MES_DRE NUMBER(2),
      PROPRIEDADE VARCHAR2(150),
      VAL_REAL_ANO_ANT NUMBER(12,3),
      PERC_REAL_ANO_ANT NUMBER(6,2),
      VAL_ORCADO NUMBER(12,3),
      PERC_ORCADO NUMBER(6,2),
      VAL_REAL NUMBER(12,3),
      PERC_REAL NUMBER(6,2),
      VAL_DIFERENCA_ORCADO_REAL NUMBER(12,3),
      PERC_DIFERENCA_ORCADO_REAL NUMBER(6,2),
      PERC_DIFERENCA_REAL_VIG_ANT NUMBER(6,2));