--DROP
--ALTER TABLE orion_ti_036 DROP CONSTRAINT fk_orion_ti_036_tipo_atividade
--DROP TABLE orion_ti_036

--ALTER TABLE orion_ti_045 DROP CONSTRAINT fk_orion_ti_045_fases
--ALTER TABLE orion_ti_045 DROP CONSTRAINT fk_orion_ti_045_tipo_atividade
--ALTER TABLE orion_ti_045 DROP CONSTRAINT fk_orion_ti_045_projeto
--DROP TABLE orion_ti_045

--ALTER TABLE orion_ti_046 DROP CONSTRAINT fk_orion_ti_046_tarefa_tipo_atividade
--ALTER TABLE orion_ti_046 DROP CONSTRAINT fk_orion_ti_046_atividades
--DROP TABLE orion_ti_046

-- Tabela Fases
CREATE TABLE orion_ti_030 (
  ID NUMBER(9) PRIMARY KEY,
  DESCRICAO VARCHAR2(400)
);

-- Tabela Tipo Atividade
CREATE TABLE orion_ti_035 (
  ID NUMBER(9) PRIMARY KEY,
  DESCRICAO VARCHAR2(400),
  EXIGE_DOC VARCHAR2(3)
);

-- Tabela Tarefa Tipo de Atividade
CREATE TABLE orion_ti_036 (
  ID NUMBER(9) PRIMARY KEY,
  ID_TIPO_ATIVIDADE NUMBER(9),
  DESCRICAO VARCHAR2(400),
  ORDENACAO NUMBER(5),
  CONSTRAINT fk_orion_ti_036_tipo_atividade FOREIGN KEY (ID_TIPO_ATIVIDADE) REFERENCES orion_ti_035(ID) ON DELETE CASCADE
);

-- Cadastro de Projetos
CREATE TABLE orion_ti_040 (
    ID NUMBER(9) PRIMARY KEY,
    COD_PROJETO NUMBER(9),
    DESCRICAO VARCHAR2(400),
    DATA_CRIACAO DATE,
    AREA VARCHAR2(400),
    DEPARTAMENTO VARCHAR2(400),
    SETOR VARCHAR2(400),
    ORIGEM_PROJETO VARCHAR2(50), -- (Plano Produto / Plano Negócios)
    SUB_ORIGEM_PROJETO VARCHAR2(50), -- (Sistemas, Integrações, Serviços, Negócios)
    STATUS VARCHAR2(100),
    OBJETIVO_PROJETO VARCHAR2(4000),
    CONTEXTUALIZACAO VARCHAR2(4000),
    DESCRICAO_PROBLEMA VARCHAR2(4000),
    PERGUNTAS_ABERTA VARCHAR2(4000),
    RISCOS VARCHAR2(4000)
);

-- Tabela Atividades
CREATE TABLE orion_ti_045 (
  ID NUMBER(9) PRIMARY KEY,
  DESCRICAO VARCHAR2(400),
  ID_PROJETO NUMBER(9),
  ID_FASE NUMBER(9),
  ID_TIPO_ATIVIDADE NUMBER(9),
  RESPONSAVEL VARCHAR2(400),
  DATA_PREV_INICIO DATE,
  DATA_PREV_FIM DATE,
  TEMPO_PREVISTO NUMBER(5),
  CONSTRAINT fk_orion_ti_045_projeto FOREIGN KEY (ID_PROJETO) REFERENCES orion_ti_040(ID) ON DELETE CASCADE
);

