CREATE TABLE ORION_ADM_010 (
  COD_CHAMADO NUMBER(9) PRIMARY KEY,
  TITULO_CHAMADO VARCHAR2(300),
  COD_REQUERENTE NUMBER(9),
  COD_TECNICO NUMBER(9),
  COD_AREA NUMBER(4),
  COD_DEPARTAMENTO NUMBER(4),
  COD_SETOR NUMBER(4),
  IMPACTO NUMBER(1) default(0),
  DESCRICAO_CHAMADO VARCHAR2(4000),
  DATA_CHAMADO DATE
);