DELETE ORION_150 O WHERE O.TIPO_META IN (6,7);

DROP TABLE ORION_COM_151;

CREATE TABLE ORION_CFC_320 (
  ID NUMBER(6),
  MES NUMBER(2),
  ANO NUMBER(4),
  PERIODO NUMBER(4),
  DIAS_UTEIS NUMBER(2),
  CAPACIDADE_DIA NUMBER(9),
  CAPACIDADE_TOTAL NUMBER(9),
  CONSTRAINT ORION_COM_151_PK PRIMARY KEY (ID)
);