// Cadastro de Servidores
CREATE TABLE ORION_TI_001 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_SERVIDOR VARCHAR2(100) NOT NULL,
    MAQUINA_FISICA NUMBER(1),
    SISTEMA_OPERACIONAL VARCHAR2(100),
    IP VARCHAR2(50),
    HD NUMBER(5),
    MEMORIA NUMBER(5),
    PROCESSADOR VARCHAR2(50),
    APLICACOES VARCHAR2(4000),
    DOCUMENTACAO BLOB
);

// Cadastro de Sistemas
CREATE TABLE ORION_TI_005 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_SISTEMA VARCHAR2(100) NOT NULL,
    OBJETIVO VARCHAR2(300),
    BANCO_DE_DADOS VARCHAR2(100),
    TIPO VARCHAR2(20),
    FORNECEDOR VARCHAR2(100),
    CNPJ VARCHAR2(20),
    ENDERECO VARCHAR2(200),
    FORMA_PAGTO VARCHAR2(50),
    TEM_CONTRATO NUMBER(1),
    CONTRATO BLOB,
    AMBIENTE VARCHAR2(50),
    USUARIOS_ATIVOS NUMBER(10),
    CAPACIDADE_USUARIOS NUMBER(10)
);

// Cadastro de Sistemas
CREATE TABLE ORION_TI_005 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_SISTEMA VARCHAR2(100) NOT NULL,
    OBJETIVO VARCHAR2(300),
    BANCO_DE_DADOS VARCHAR2(100),
    TIPO VARCHAR2(20),
    FORNECEDOR VARCHAR2(100),
    CNPJ VARCHAR2(20),
    ENDERECO VARCHAR2(200),
    FORMA_PAGTO VARCHAR2(50),
    TEM_CONTRATO NUMBER(1),
    CONTRATO BLOB,
    AMBIENTE VARCHAR2(50),
    USUARIOS_ATIVOS NUMBER(10),
    CAPACIDADE_USUARIOS NUMBER(10)
);

// Cadastro de Sistemas
CREATE TABLE ORION_TI_005 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_SISTEMA VARCHAR2(100) NOT NULL,
    OBJETIVO VARCHAR2(300),
    BANCO_DE_DADOS VARCHAR2(100),
    TIPO VARCHAR2(20),
    FORNECEDOR VARCHAR2(100),
    CNPJ VARCHAR2(20),
    ENDERECO VARCHAR2(200),
    FORMA_PAGTO VARCHAR2(50),
    TEM_CONTRATO NUMBER(1),
    CONTRATO BLOB,
    AMBIENTE VARCHAR2(50),
    USUARIOS_ATIVOS NUMBER(10),
    CAPACIDADE_USUARIOS NUMBER(10)
);

// Cadastro de Integracoes
CREATE TABLE ORION_TI_010 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_INTEGRACAO VARCHAR2(100) NOT NULL,
    OBJETIVO VARCHAR2(300),
    TIPO VARCHAR2(20),
    SISTEMA_ORIGEM NUMBER(5),
    SISTEMA_DESTINO NUMBER(5),
    SERVIDOR NUMBER(5),
    FORNECEDOR VARCHAR2(100),
    CNPJ VARCHAR2(20),
    ENDERECO VARCHAR2(200),
    TIPO_INTEGRACAO VARCHAR2(50)
);

// Cadastro de Servicos
CREATE TABLE ORION_TI_015 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_SERVICO VARCHAR2(100) NOT NULL,
    OBJETIVO VARCHAR2(300),
    TIME_RESPONSAVEL VARCHAR2(50),
    DISPONIBILIDADE VARCHAR2(50),
    TECNICOS_FORNECEDORES VARCHAR2(400)
);