CREATE TABLE orion_com_260(
       id                 NUMBER, 
       tipo               NUMBER(2), 
       forma_pagamento    NUMBER(3), 
       portador           NUMBER(3), 
       cnpj9              NUMBER(9),
       cnpj4              NUMBER(4),
       cnpj2              NUMBER(2),
       cod_funcionario    NUMBER(6), 
       desc_capa          NUMBER(10,2),
       tipo_pedido        NUMBER(1),
       deposito_itens     NUMBER(3),
       desc_max_cliente   NUMBER(10,2),
       comissao           NUMBER(10,2),
       Cond_pgto          NUMBER(3),
       franchising        NUMBER(3),
       natureza_operacao  NUMBER(3),
       desconto           NUMBER(10,2),
       CONSTRAINT orion_cfc_260_pk PRIMARY KEY (id));