// Cadastro de Servidores
CREATE TABLE ORION_TI_001 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_SERVIDOR VARCHAR2(100) NOT NULL,
    MAQUINA_FISICA NUMBER(1),
    SISTEMA_OPERACIONAL VARCHAR2(100),
    IP VARCHAR2(50),
    HD NUMBER(5),
    MEMORIA NUMBER(5),
    PROCESSADOR VARCHAR2(50),
    APLICACOES VARCHAR2(4000),
    DOCUMENTACAO BLOB
);

// Cadastro de Sistemas
CREATE TABLE ORION_TI_005 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_SISTEMA VARCHAR2(100) NOT NULL,
    OBJETIVO VARCHAR2(300),
    BANCO_DE_DADOS VARCHAR2(100),
    TIPO VARCHAR2(20),
    FORNECEDOR VARCHAR2(100),
    CNPJ VARCHAR2(20),
    ENDERECO VARCHAR2(200),
    FORMA_PAGTO VARCHAR2(50),
    TEM_CONTRATO NUMBER(1),
    CONTRATO BLOB,
    AMBIENTE VARCHAR2(50),
    USUARIOS_ATIVOS NUMBER(10),
    CAPACIDADE_USUARIOS NUMBER(10)
);

// Cadastro de Integração
CREATE TABLE ORION_TI_010 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_INTEGRACAO VARCHAR2(100) NOT NULL,
    OBJETIVO VARCHAR2(300),
    TIPO_INTEGRACAO VARCHAR2(50)
    TIPO_CONEXAO VARCHAR2(20),
    SISTEMA_ORIGEM NUMBER(5),
    SISTEMA_DESTINO NUMBER(5),
    SERVIDOR NUMBER(5),
    FORNECEDOR VARCHAR2(100),
    CNPJ VARCHAR2(20),
    ENDERECO VARCHAR2(200),
    CONSTRAINT fk_orion_ti_005_sistema_origem FOREIGN KEY (SISTEMA_ORIGEM) REFERENCES ORION_TI_005 (ID),
    CONSTRAINT fk_orion_ti_005_sistema_destino FOREIGN KEY (SISTEMA_DESTINO) REFERENCES ORION_TI_005 (ID),
    CONSTRAINT fk_orion_ti_001_servidor FOREIGN KEY (SERVIDOR) REFERENCES ORION_TI_001 (ID)
);

// Cadastro de Serviços
CREATE TABLE ORION_TI_015 (
    ID NUMBER(5) PRIMARY KEY,
    NOME_SERVICO VARCHAR2(100) NOT NULL,
    OBJETIVO VARCHAR2(300),
    TIME_RESPONSAVEL VARCHAR2(50),
    DISPONIBILIDADE NUMBER(1),
    TECNICOS_FORNECEDORES VARCHAR2(200)
);

// ALTERADO TAMANNHO DO CAMPO PROCESSADOR PARA 200
ALTER TABLE orion_ti_001
MODIFY processador VARCHAR2(200);


// ALTERA CAMPO HD E MEMÓRIA PARA VARCHAR2(100)
ALTER TABLE ORION_TI_001 ADD HD_NEW VARCHAR2(100);
ALTER TABLE ORION_TI_001 ADD MEMORIA_NEW VARCHAR2(100);

UPDATE ORION_TI_001 SET HD_NEW = HD;
UPDATE ORION_TI_001 SET MEMORIA_NEW = MEMORIA;

UPDATE ORION_TI_001 SET HD = NULL;
UPDATE ORION_TI_001 SET MEMORIA = NULL;

ALTER TABLE ORION_TI_001 MODIFY HD VARCHAR2(100);
ALTER TABLE ORION_TI_001 MODIFY MEMORIA VARCHAR2(100);

UPDATE ORION_TI_001 SET HD = HD_NEW;
UPDATE ORION_TI_001 SET MEMORIA = MEMORIA_NEW;

ALTER TABLE ORION_TI_001 DROP COLUMN HD_NEW;
ALTER TABLE ORION_TI_001 DROP COLUMN MEMORIA_NEW;